apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-config-bnb
data:
  API_KEY: ""
  API_SECRET: ""
  GRID_NUM: "10"
  MAX_POSITION: "1.0"
  GRID_INTERVAL: "28"
  HALF_SPREAD: "36"
  SKEW: "1.2"
  LOOKING_DEPTH: "0.0"
  INSTRUMENT_ID: "BNBUSDT-PERP.BINANCE"
  MAX_TRADE_SIZE: "0.1"
  CONNECTION_TIME_OUT: "30"
  RECONCILIATION_TIME_OUT: "10"
  PORTFOLIO_TIME_OUT: "10"
  DISCONNECTION_TIME_OUT: "10"
  POST_STOP_TIME_OUT: "5"
  INFLIGHT_CHECK_RETRY: "20"
  MIN_SECONDS_BETWEEN_TRIGGERS: "0.2"
  SPREAD_MIN_THRESHOLD: "2"
  SPREAD_ADJUSTED_FACTOR: "1.2"
  INTERVAL_ADJUSTED_FACTOR: "1.2"
  AVOID_REPEATED_FACTOR: "3.0"
