apiVersion: v1
kind: Pod
metadata:
  name: trading-bot-bnb
spec:
  restartPolicy: Always
  containers:
  - name: trading-container
    image: ghcr.io/xingyanan/nautilus_trader:develop
    imagePullPolicy: Always
    command: ["/bin/bash", "-c"]
    args: ["/app/deployment/run.sh"]
    env:
      # 从 ConfigMap 加载环境变量
    - name: GRID_NUM
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: GRID_NUM
    - name: MAX_POSITION
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: MAX_POSITION
    - name: GRID_INTERVAL
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: GRID_INTERVAL
    - name: HALF_SPREAD
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: HALF_SPREAD
    - name: SKEW
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: SKEW
    - name: LOOKING_DEPTH
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: LOOKING_DEPTH
    - name: ADJUSTED_FACTOR
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: ADJUSTED_FACTOR
    - name: INSTRUMENT_ID
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: INSTRUMENT_ID
    - name: MAX_TRADE_SIZE
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: MAX_TRADE_SIZE
    - name: CONNECTION_TIME_OUT
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: CONNECTION_TIME_OUT
    - name: RECONCILIATION_TIME_OUT
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: RECONCILIATION_TIME_OUT
    - name: PORTFOLIO_TIME_OUT
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: PORTFOLIO_TIME_OUT
    - name: DISCONNECTION_TIME_OUT
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: DISCONNECTION_TIME_OUT
    - name: POST_STOP_TIME_OUT
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: POST_STOP_TIME_OUT
    - name: INFLIGHT_CHECK_RETRY
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: INFLIGHT_CHECK_RETRY
      # 从 Secret 加载环境变量
    - name: API_KEY
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: API_KEY
    - name: API_SECRET
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: API_SECRET
    - name: MIN_SECONDS_BETWEEN_TRIGGERS
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: MIN_SECONDS_BETWEEN_TRIGGERS
    - name: SPREAD_MIN_THRESHOLD
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: SPREAD_MIN_THRESHOLD
    - name: SPREAD_ADJUSTED_FACTOR
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: SPREAD_ADJUSTED_FACTOR
    - name: INTERVAL_ADJUSTED_FACTOR
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: INTERVAL_ADJUSTED_FACTOR
    - name: AVOID_REPEATED_FACTOR
      valueFrom:
        configMapKeyRef:
          name: trading-config-bnb
          key: AVOID_REPEATED_FACTOR
